---
kind: pipeline
type: docker
name: build_drone_enhanced

steps:
  - name: build
    image: golang:1.15
    commands:
      - export GO111MODULE=on
      - go get -u -v github.com/prometheus/promu@v0.12.0
      - promu build
      - ./drone_enhanced version
