---
kind: pipeline
type: docker
name: nightly build

steps:
  - name: build
    image: golang:1.15
    commands:
      - make build
      - ./drone-enhanced version

  - name: release nightly docker
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: ifooth/drone-enhanced
      tags:
        - latest

---
kind: pipeline
type: docker
name: release

steps:
  - name: build
    image: golang:1.15
    commands:
      - make build
      - ./drone-enhanced version
      - echo -n "v`cat VERSION`" > .tags

  - name: release docker
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: ifooth/drone-enhanced

  - name: release binaries
    image: docker:20.10.7
    commands:
      - |
        wget -q https://github.com/prometheus/promu/releases/download/v0.12.0/promu-0.12.0.linux-amd64.tar.gz && \
        tar -xf promu-0.12.0.linux-amd64.tar.gz && \
        mv promu-0.12.0.linux-amd64/promu /bin && \
        rm -rf promu-*
      - promu crossbuild
      - promu crossbuild tarballs
      - promu checksum .tarballs
      - promu release .tarballs
    environment:
      GITHUB_TOKEN:
        from_secret: GITHUB_TOKEN
