---
kind: pipeline
type: docker
name: build-drone-enhanced

steps:
  - name: build
    image: golang:1.15
    commands:
      - export GO111MODULE=on
      - go get -u -v github.com/prometheus/promu@v0.12.0
      - promu build
      - ./drone-enhanced version

  - name: build docker
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: ifooth/drone-enhanced
      tags:
        - latest

---
kind: pipeline
type: docker
name: release

steps:
  - name: build
    image: ifooth/promu:v0.12.0
    commands:
      - promu build
      - echo -n "v`cat VERSION`" > .tags

  - name: release docker
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: ifooth/drone-enhanced

  - name: release binaries
    image: ifooth/promu:v0.12.0
    commands:
      - promu crossbuild tarballs
      - promu checksum .tarballs
      - promu release .tarballs
