---
kind: pipeline
type: docker
name: nightly build

steps:
  - name: build
    image: golang:1.15
    commands:
      - make build
      - ./drone-enhanced version

  - name: build docker
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: ifooth/drone-enhanced
      tags:
        - latest

---
kind: pipeline
type: docker
name: release

steps:
  - name: build
    image: golang:1.15
    commands:
      - make build
      - ./drone-enhanced version
      - echo -n "v`cat VERSION`" > .tags

  - name: release docker
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: ifooth/drone-enhanced

  - name: release binaries
    image: golang:1.15
    commands:
      - make build
      - promu crossbuild
      - promu crossbuild tarballs
      - promu checksum .tarballs
      - promu release .tarballs
    environment:
      GITHUB_TOKEN:
        from_secret: GITHUB_TOKEN
