go:
  version: 1.15.1
  cgo: false
repository:
  path: github.com/ifooth/drone-enhanced
build:
  binaries:
    - name: drone-enhanced
      path: cmd
  flags: -a -tags netgo
  ldflags: |
    -X github.com/prometheus/common/version.Version={{.Version}}
    -X github.com/prometheus/common/version.Revision={{.Revision}}
    -X github.com/prometheus/common/version.Branch={{.Branch}}
    -X github.com/prometheus/common/version.BuildUser={{user}}@{{host}}
    -X github.com/prometheus/common/version.BuildDate={{date "20060102-15:04:05"}}
tarball:
  files:
    - drone-enhanced
crossbuild:
  platforms:
    - linux/amd64
    - darwin/amd64
    - windows/amd64
