verbose: false
go:
  version: 1.15.1
  cgo: false
repository:
  path: github.com/ifooth/drone-enhanced
build:
  binaries:
    - name: drone-enhanced
      path: cmd
  flags: -a -tags netgo
  ldflags: |
    -s
    -X {{repoPath}}/version.Version={{.Version}}
    -X {{repoPath}}/version.Revision={{.Revision}}
    -X {{repoPath}}/version.Branch={{.Branch}}
    -X {{repoPath}}/version.BuildUser={{user}}@{{host}}
    -X {{repoPath}}/version.BuildDate={{date "20060102-15:04:05"}}
crossbuild:
  platforms:
    - linux/amd64
    - darwin/amd64
