name: Go

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Build
        run: make promu && make build

      - name: Version
        run: ./drone-enhanced version

  cross-build-check:
    runs-on: ubuntu-latest
    name: Go build for different platform
    steps:
      - name: Install Go.
        uses: actions/setup-go@v1
        with:
          go-version: 1.15.x

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}

      - name: Cross build check.
        run: |
          make promu
          /home/runner/go/bin/promu crossbuild
