name: Release
on:
  workflow_dispatch:
    inputs:
      branch:
        description: "发布的分支"
        required: true
        default: "main"

jobs:
  cross-build-check:
    runs-on: ubuntu-latest
    name: Go build for different platform
    steps:
      - name: Install Go.
        uses: actions/setup-go@v1
        with:
          go-version: 1.15.x

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}

      - name: Cross build check.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          make promu
          export PATH="`go env GOPATH`/bin;$PATH"
          /home/runner/go/bin/promu crossbuild
          /home/runner/go/bin/promu crossbuild tarballs
          /home/runner/go/bin/promu checksum .tarballs
          /home/runner/go/bin/promu release .tarballs
